package com.openswift.keyboard.voice

import android.content.Context
import android.content.Intent
import android.media.AudioManager
import android.os.Handler
import android.os.Looper
import android.speech.RecognizerIntent
import android.speech.SpeechRecognizer
import java.util.*

/**
 * High-speed, responsive, and completely silent voice input manager:
 * - Real-time streaming transcription with partial results.
 * - Auto-stops after 15 seconds if no speech is detected.
 * - Mutes start and stop beeps during recognition so input is completely quiet.
 * - Suppresses all error toasts and intrusive dialogs.
 * - Restarts recognition seamlessly across pauses in continuous mode.
 */
class VoiceRecognizer(private val ctx: Context) {

    var onPartialResult: ((String) -> Unit)? = null
    var onResult: ((String) -> Unit)? = null
    var onStateChanged: ((Boolean) -> Unit)? = null
    var onError: ((String) -> Unit)? = null

    private var recognizer: SpeechRecognizer? = null
    private var isListening = false
    private var isContinuous = false
    private var currentLanguage: String = Locale.getDefault().language
    private val mainHandler = Handler(Looper.getMainLooper())
    private val audioManager = ctx.getSystemService(Context.AUDIO_SERVICE) as? AudioManager

    private val audioStreamsToMute = intArrayOf(
        AudioManager.STREAM_SYSTEM,
        AudioManager.STREAM_NOTIFICATION,
        AudioManager.STREAM_MUSIC,
        AudioManager.STREAM_ALARM,
    )
    private val savedVolumes = mutableMapOf<Int, Int>()
    private var isMuted = false
    private var unmuteRunnable: Runnable? = null

    private val silenceTimeoutRunnable = Runnable {
        // Automatically stop after 7 seconds if no speech is detected
        if (isListening || isContinuous) {
            stopListening()
        }
    }

    private fun resetSilenceTimer() {
        mainHandler.removeCallbacks(silenceTimeoutRunnable)
        if (isListening || isContinuous) {
            mainHandler.postDelayed(silenceTimeoutRunnable, SILENCE_TIMEOUT_MS)
        }
    }

    /**
     * Mutes STREAM_SYSTEM, STREAM_NOTIFICATION, and STREAM_MUSIC so that start and
     * stop beeps/earcons generated by the system SpeechRecognizer are completely silent.
     */
    private fun muteAllBeeps() {
        val am = audioManager ?: return
        try {
            unmuteRunnable?.let { mainHandler.removeCallbacks(it) }
            unmuteRunnable = null
            for (stream in audioStreamsToMute) {
                try {
                    if (!savedVolumes.containsKey(stream)) {
                        savedVolumes[stream] = am.getStreamVolume(stream)
                    }
                    am.adjustStreamVolume(stream, AudioManager.ADJUST_MUTE, 0)
                    am.setStreamVolume(stream, 0, 0)
                } catch (_: Exception) {}
            }
            isMuted = true
        } catch (_: Exception) {}
    }

    /**
     * Safely restores audio stream volumes after speech recognition finishes,
     * with a delay so that any delayed system stop-tones are caught in silence.
     */
    private fun restoreBeepsDelayed(delayMs: Long = 800L) {
        val am = audioManager ?: return
        unmuteRunnable?.let { mainHandler.removeCallbacks(it) }
        val runnable = Runnable {
            try {
                if (isMuted) {
                    for ((stream, originalVol) in savedVolumes) {
                        try {
                            am.adjustStreamVolume(stream, AudioManager.ADJUST_UNMUTE, 0)
                            am.setStreamVolume(stream, originalVol, 0)
                        } catch (_: Exception) {}
                    }
                    savedVolumes.clear()
                    isMuted = false
                }
            } catch (_: Exception) {}
            unmuteRunnable = null
        }
        unmuteRunnable = runnable
        mainHandler.postDelayed(runnable, delayMs)
    }

    fun prewarm() {
        initRecognizer()
    }

    private fun initRecognizer(): Boolean {
        if (recognizer == null) {
            try {
                recognizer = SpeechRecognizer.createSpeechRecognizer(ctx.applicationContext)
            } catch (_: Exception) {
                try {
                    recognizer = SpeechRecognizer.createSpeechRecognizer(ctx)
                } catch (_: Exception) {
                    return false
                }
            }
            recognizer?.setRecognitionListener(object : android.speech.RecognitionListener {
                override fun onReadyForSpeech(params: android.os.Bundle?) {
                    resetSilenceTimer()
                }

                override fun onBeginningOfSpeech() {
                    resetSilenceTimer()
                }

                override fun onRmsChanged(rmsdB: Float) {
                    if (rmsdB > 2.0f) {
                        resetSilenceTimer()
                    }
                }

                override fun onBufferReceived(buffer: ByteArray?) {}
                override fun onEndOfSpeech() {}

                override fun onPartialResults(results: android.os.Bundle?) {
                    val matches = results?.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION)
                    val text = matches?.firstOrNull()?.trim()
                    if (!text.isNullOrEmpty()) {
                        resetSilenceTimer()
                        onPartialResult?.invoke(text)
                    }
                }

                override fun onResults(results: android.os.Bundle?) {
                    val matches = results?.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION)
                    val text = matches?.firstOrNull()?.trim()
                    if (!text.isNullOrEmpty()) {
                        resetSilenceTimer()
                        onResult?.invoke(text)
                    }

                    // Keep listening continuously across pauses
                    if (isContinuous) {
                        mainHandler.postDelayed({
                            if (isContinuous && isListening) {
                                restartRecognitionSession()
                            }
                        }, 150L)
                    } else {
                        stopListening()
                    }
                }

                override fun onError(error: Int) {
                    if (!isListening && !isContinuous) return

                    val canRetry = (error == SpeechRecognizer.ERROR_NO_MATCH ||
                            error == SpeechRecognizer.ERROR_SPEECH_TIMEOUT ||
                            error == SpeechRecognizer.ERROR_NETWORK_TIMEOUT ||
                            error == SpeechRecognizer.ERROR_CLIENT ||
                            error == SpeechRecognizer.ERROR_RECOGNIZER_BUSY)

                    if (isContinuous && canRetry) {
                        // Restart recognition session silently without showing error
                        mainHandler.postDelayed({
                            if (isContinuous && isListening) {
                                restartRecognitionSession()
                            }
                        }, 200L)
                        return
                    }

                    // On non-retryable error, stop silently without error message
                    isListening = false
                    isContinuous = false
                    mainHandler.removeCallbacks(silenceTimeoutRunnable)
                    onStateChanged?.invoke(false)
                    onError?.invoke("")
                }

                override fun onEvent(eventType: Int, params: android.os.Bundle?) {}
            })
        }
        return recognizer != null
    }

    private fun restartRecognitionSession() {
        if (!isContinuous || !isListening) return
        muteAllBeeps()
        try {
            recognizer?.cancel()
        } catch (_: Exception) {}
        try {
            val intent = buildIntent()
            recognizer?.startListening(intent)
        } catch (_: Exception) {
            recreateRecognizer()
            try {
                recognizer?.startListening(buildIntent())
            } catch (_: Exception) {
                isListening = false
                isContinuous = false
                mainHandler.removeCallbacks(silenceTimeoutRunnable)
                restoreBeepsDelayed(400L)
                onStateChanged?.invoke(false)
            }
        }
    }

    private fun recreateRecognizer() {
        try {
            recognizer?.cancel()
            recognizer?.destroy()
        } catch (_: Exception) {}
        recognizer = null
        initRecognizer()
    }

    private fun buildIntent(): Intent {
        return Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH).apply {
            putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL, RecognizerIntent.LANGUAGE_MODEL_FREE_FORM)
            putExtra(RecognizerIntent.EXTRA_LANGUAGE, currentLanguage)
            putExtra(RecognizerIntent.EXTRA_LANGUAGE_PREFERENCE, currentLanguage)
            putExtra(RecognizerIntent.EXTRA_PARTIAL_RESULTS, true)
            putExtra(RecognizerIntent.EXTRA_MAX_RESULTS, 3)
            putExtra(RecognizerIntent.EXTRA_CALLING_PACKAGE, ctx.packageName)
            // Low-latency continuous dictation parameters
            putExtra("android.speech.extra.DICTATION_MODE", true)
            putExtra(RecognizerIntent.EXTRA_SPEECH_INPUT_MINIMUM_LENGTH_MILLIS, 1000L)
            putExtra(RecognizerIntent.EXTRA_SPEECH_INPUT_COMPLETE_SILENCE_LENGTH_MILLIS, 1200L)
            putExtra(RecognizerIntent.EXTRA_SPEECH_INPUT_POSSIBLY_COMPLETE_SILENCE_LENGTH_MILLIS, 1000L)
        }
    }

    fun startListening(languageCode: String? = null, continuous: Boolean = true) {
        currentLanguage = languageCode ?: Locale.getDefault().language
        isContinuous = continuous
        isListening = true

        muteAllBeeps()

        if (!initRecognizer()) {
            isListening = false
            isContinuous = false
            restoreBeepsDelayed(200L)
            onStateChanged?.invoke(false)
            return
        }

        try {
            recognizer?.startListening(buildIntent())
            resetSilenceTimer()
            onStateChanged?.invoke(true)
        } catch (_: Exception) {
            recreateRecognizer()
            try {
                recognizer?.startListening(buildIntent())
                resetSilenceTimer()
                onStateChanged?.invoke(true)
            } catch (_: Exception) {
                isListening = false
                isContinuous = false
                mainHandler.removeCallbacks(silenceTimeoutRunnable)
                restoreBeepsDelayed(400L)
                onStateChanged?.invoke(false)
            }
        }
    }

    fun stopListening() {
        isContinuous = false
        isListening = false
        mainHandler.removeCallbacks(silenceTimeoutRunnable)
        muteAllBeeps()
        try {
            recognizer?.cancel()
        } catch (_: Exception) {}
        try {
            recognizer?.stopListening()
        } catch (_: Exception) {}
        onStateChanged?.invoke(false)
        restoreBeepsDelayed(800L)
    }

    fun destroy() {
        isContinuous = false
        isListening = false
        mainHandler.removeCallbacks(silenceTimeoutRunnable)
        mainHandler.removeCallbacksAndMessages(null)
        unmuteRunnable?.let { mainHandler.removeCallbacks(it) }
        unmuteRunnable = null
        try {
            recognizer?.cancel()
        } catch (_: Exception) {}
        try {
            recognizer?.destroy()
        } catch (_: Exception) {}
        recognizer = null
        // Immediately restore volumes when destroyed
        val am = audioManager
        if (am != null && isMuted) {
            for ((stream, originalVol) in savedVolumes) {
                try {
                    am.adjustStreamVolume(stream, AudioManager.ADJUST_UNMUTE, 0)
                    am.setStreamVolume(stream, originalVol, 0)
                } catch (_: Exception) {}
            }
            savedVolumes.clear()
            isMuted = false
        }
        onStateChanged?.invoke(false)
    }

    companion object {
        const val SILENCE_TIMEOUT_MS = 7_000L
    }
}
